### ISSUE TITLE
Design Hills Area 03 (Chemical Craters)

### ISSUE THREAD

**Issue by alyg563** [AztecGameLab/LongTermGame7#138]
Story document: https://docs.google.com/document/d/1Yrxwuv9HOGtcq2lruRMUnvdwHG1_AMKlU_cYMGU4YQw/edit?usp=sharing

**Comment by ratmonky** [comment]
![Image](https://user-images.githubusercontent.com/123781545/219561349-423972bc-aec3-4f84-921f-0f9a45168dcb.png)

Note 1: The player starts at a small patch of abandoned houses, in one of them they find a gas mask, in the other, they find extra filters, and in the last a lore thing. The player must pick up the gas mask and the additional filters to enter the area (the gas mask will only have a small amount of durability left so they need more filters) 

Note 2: A small research tent with a note from the disgruntled scientist, mentioning that there was once a plant that consumed the toxic chemicals in the air, purifying the toxic fumes in the area. It has gone extinct, except for a sample in the mini-lab, the player must find 3 keys in order to open the container and acquire the plant. The scientist left his key so the player needs to find 2 more.

Note 3: Here in the small lab the player can see samples of monsters and a dead sample of the special plant, as well as seeds. the player will read that when the plant dies, the plant dries and ignites because of the sun, creating an incredibly purifying smoke. In the lab, there will also be a note saying that a scientist dropped their key inside a crater north of the lab and a note or something saying that a scientist went to investigate a monster burrow, and never came back. (Player will need to use a water monster to peek inside the craters and find a key, and an earth pokemon to open a caved-in monster burrow, and find another key)

Note 4: Monster Burrow where the key is, I thought that there could be a mini-boss or just a scripted fight that the player must win to get the key.

Note 5: When the player gets here the camera will pan forward to show an abundance of craters, resulting in an especially toxic atmosphere, the simple gas mask is not enough to protect the player. After planting the seeds of the plant, the player will ignite the dead plant with a fire monster, releasing the purifying smoke and allowing the player to walk past the long stretch of craters.
